# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain.channel.citrix.rest.client:
        class: CampaignChain\Channel\CitrixBundle\REST\CitrixClient
        calls:
            - [setContainer, ["@service_container"]]
